// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: quota/quota.proto

package quota

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReserveSubscriptionSlotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SagaId         string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	SubscriptionId int64                  `protobuf:"varint,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Email          string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveSubscriptionSlotRequest) Reset() {
	*x = ReserveSubscriptionSlotRequest{}
	mi := &file_quota_quota_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveSubscriptionSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveSubscriptionSlotRequest) ProtoMessage() {}

func (x *ReserveSubscriptionSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quota_quota_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveSubscriptionSlotRequest.ProtoReflect.Descriptor instead.
func (*ReserveSubscriptionSlotRequest) Descriptor() ([]byte, []int) {
	return file_quota_quota_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveSubscriptionSlotRequest) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *ReserveSubscriptionSlotRequest) GetSubscriptionId() int64 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

func (x *ReserveSubscriptionSlotRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ReserveSubscriptionSlotResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Reserved        bool                   `protobuf:"varint,1,opt,name=reserved,proto3" json:"reserved,omitempty"`
	RejectionReason string                 `protobuf:"bytes,2,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReserveSubscriptionSlotResponse) Reset() {
	*x = ReserveSubscriptionSlotResponse{}
	mi := &file_quota_quota_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveSubscriptionSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveSubscriptionSlotResponse) ProtoMessage() {}

func (x *ReserveSubscriptionSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quota_quota_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveSubscriptionSlotResponse.ProtoReflect.Descriptor instead.
func (*ReserveSubscriptionSlotResponse) Descriptor() ([]byte, []int) {
	return file_quota_quota_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveSubscriptionSlotResponse) GetReserved() bool {
	if x != nil {
		return x.Reserved
	}
	return false
}

func (x *ReserveSubscriptionSlotResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

type CommitSubscriptionSlotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId int64                  `protobuf:"varint,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitSubscriptionSlotRequest) Reset() {
	*x = CommitSubscriptionSlotRequest{}
	mi := &file_quota_quota_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitSubscriptionSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitSubscriptionSlotRequest) ProtoMessage() {}

func (x *CommitSubscriptionSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quota_quota_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitSubscriptionSlotRequest.ProtoReflect.Descriptor instead.
func (*CommitSubscriptionSlotRequest) Descriptor() ([]byte, []int) {
	return file_quota_quota_proto_rawDescGZIP(), []int{2}
}

func (x *CommitSubscriptionSlotRequest) GetSubscriptionId() int64 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

type CommitSubscriptionSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitSubscriptionSlotResponse) Reset() {
	*x = CommitSubscriptionSlotResponse{}
	mi := &file_quota_quota_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitSubscriptionSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitSubscriptionSlotResponse) ProtoMessage() {}

func (x *CommitSubscriptionSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quota_quota_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitSubscriptionSlotResponse.ProtoReflect.Descriptor instead.
func (*CommitSubscriptionSlotResponse) Descriptor() ([]byte, []int) {
	return file_quota_quota_proto_rawDescGZIP(), []int{3}
}

type ReleaseSubscriptionSlotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId int64                  `protobuf:"varint,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReleaseSubscriptionSlotRequest) Reset() {
	*x = ReleaseSubscriptionSlotRequest{}
	mi := &file_quota_quota_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSubscriptionSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSubscriptionSlotRequest) ProtoMessage() {}

func (x *ReleaseSubscriptionSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quota_quota_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSubscriptionSlotRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSubscriptionSlotRequest) Descriptor() ([]byte, []int) {
	return file_quota_quota_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseSubscriptionSlotRequest) GetSubscriptionId() int64 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

type ReleaseSubscriptionSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSubscriptionSlotResponse) Reset() {
	*x = ReleaseSubscriptionSlotResponse{}
	mi := &file_quota_quota_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSubscriptionSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSubscriptionSlotResponse) ProtoMessage() {}

func (x *ReleaseSubscriptionSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quota_quota_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSubscriptionSlotResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSubscriptionSlotResponse) Descriptor() ([]byte, []int) {
	return file_quota_quota_proto_rawDescGZIP(), []int{5}
}

var File_quota_quota_proto protoreflect.FileDescriptor

const file_quota_quota_proto_rawDesc = "" +
	"\n" +
	"\x11quota/quota.proto\x12\x05quota\"x\n" +
	"\x1eReserveSubscriptionSlotRequest\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\x03R\x0esubscriptionId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"h\n" +
	"\x1fReserveSubscriptionSlotResponse\x12\x1a\n" +
	"\breserved\x18\x01 \x01(\bR\breserved\x12)\n" +
	"\x10rejection_reason\x18\x02 \x01(\tR\x0frejectionReason\"H\n" +
	"\x1dCommitSubscriptionSlotRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\x03R\x0esubscriptionId\" \n" +
	"\x1eCommitSubscriptionSlotResponse\"I\n" +
	"\x1eReleaseSubscriptionSlotRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\x03R\x0esubscriptionId\"!\n" +
	"\x1fReleaseSubscriptionSlotResponse2\xc9\x02\n" +
	"\fQuotaService\x12h\n" +
	"\x17ReserveSubscriptionSlot\x12%.quota.ReserveSubscriptionSlotRequest\x1a&.quota.ReserveSubscriptionSlotResponse\x12e\n" +
	"\x16CommitSubscriptionSlot\x12$.quota.CommitSubscriptionSlotRequest\x1a%.quota.CommitSubscriptionSlotResponse\x12h\n" +
	"\x17ReleaseSubscriptionSlot\x12%.quota.ReleaseSubscriptionSlotRequest\x1a&.quota.ReleaseSubscriptionSlotResponseB3Z1github-release-notifier/pkg/contracts/quota;quotab\x06proto3"

var (
	file_quota_quota_proto_rawDescOnce sync.Once
	file_quota_quota_proto_rawDescData []byte
)

func file_quota_quota_proto_rawDescGZIP() []byte {
	file_quota_quota_proto_rawDescOnce.Do(func() {
		file_quota_quota_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quota_quota_proto_rawDesc), len(file_quota_quota_proto_rawDesc)))
	})
	return file_quota_quota_proto_rawDescData
}

var file_quota_quota_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_quota_quota_proto_goTypes = []any{
	(*ReserveSubscriptionSlotRequest)(nil),  // 0: quota.ReserveSubscriptionSlotRequest
	(*ReserveSubscriptionSlotResponse)(nil), // 1: quota.ReserveSubscriptionSlotResponse
	(*CommitSubscriptionSlotRequest)(nil),   // 2: quota.CommitSubscriptionSlotRequest
	(*CommitSubscriptionSlotResponse)(nil),  // 3: quota.CommitSubscriptionSlotResponse
	(*ReleaseSubscriptionSlotRequest)(nil),  // 4: quota.ReleaseSubscriptionSlotRequest
	(*ReleaseSubscriptionSlotResponse)(nil), // 5: quota.ReleaseSubscriptionSlotResponse
}
var file_quota_quota_proto_depIdxs = []int32{
	0, // 0: quota.QuotaService.ReserveSubscriptionSlot:input_type -> quota.ReserveSubscriptionSlotRequest
	2, // 1: quota.QuotaService.CommitSubscriptionSlot:input_type -> quota.CommitSubscriptionSlotRequest
	4, // 2: quota.QuotaService.ReleaseSubscriptionSlot:input_type -> quota.ReleaseSubscriptionSlotRequest
	1, // 3: quota.QuotaService.ReserveSubscriptionSlot:output_type -> quota.ReserveSubscriptionSlotResponse
	3, // 4: quota.QuotaService.CommitSubscriptionSlot:output_type -> quota.CommitSubscriptionSlotResponse
	5, // 5: quota.QuotaService.ReleaseSubscriptionSlot:output_type -> quota.ReleaseSubscriptionSlotResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_quota_quota_proto_init() }
func file_quota_quota_proto_init() {
	if File_quota_quota_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quota_quota_proto_rawDesc), len(file_quota_quota_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quota_quota_proto_goTypes,
		DependencyIndexes: file_quota_quota_proto_depIdxs,
		MessageInfos:      file_quota_quota_proto_msgTypes,
	}.Build()
	File_quota_quota_proto = out.File
	file_quota_quota_proto_goTypes = nil
	file_quota_quota_proto_depIdxs = nil
}
