// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/quota/quota.proto

package quota

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuotaService_ReserveSubscriptionSlot_FullMethodName = "/quota.QuotaService/ReserveSubscriptionSlot"
	QuotaService_CommitSubscriptionSlot_FullMethodName  = "/quota.QuotaService/CommitSubscriptionSlot"
	QuotaService_ReleaseSubscriptionSlot_FullMethodName = "/quota.QuotaService/ReleaseSubscriptionSlot"
)

// QuotaServiceClient is the client API for QuotaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuotaServiceClient interface {
	ReserveSubscriptionSlot(ctx context.Context, in *ReserveSubscriptionSlotRequest, opts ...grpc.CallOption) (*ReserveSubscriptionSlotResponse, error)
	CommitSubscriptionSlot(ctx context.Context, in *CommitSubscriptionSlotRequest, opts ...grpc.CallOption) (*CommitSubscriptionSlotResponse, error)
	ReleaseSubscriptionSlot(ctx context.Context, in *ReleaseSubscriptionSlotRequest, opts ...grpc.CallOption) (*ReleaseSubscriptionSlotResponse, error)
}

type quotaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuotaServiceClient(cc grpc.ClientConnInterface) QuotaServiceClient {
	return &quotaServiceClient{cc}
}

func (c *quotaServiceClient) ReserveSubscriptionSlot(ctx context.Context, in *ReserveSubscriptionSlotRequest, opts ...grpc.CallOption) (*ReserveSubscriptionSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveSubscriptionSlotResponse)
	err := c.cc.Invoke(ctx, QuotaService_ReserveSubscriptionSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quotaServiceClient) CommitSubscriptionSlot(ctx context.Context, in *CommitSubscriptionSlotRequest, opts ...grpc.CallOption) (*CommitSubscriptionSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitSubscriptionSlotResponse)
	err := c.cc.Invoke(ctx, QuotaService_CommitSubscriptionSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quotaServiceClient) ReleaseSubscriptionSlot(ctx context.Context, in *ReleaseSubscriptionSlotRequest, opts ...grpc.CallOption) (*ReleaseSubscriptionSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSubscriptionSlotResponse)
	err := c.cc.Invoke(ctx, QuotaService_ReleaseSubscriptionSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuotaServiceServer is the server API for QuotaService service.
// All implementations must embed UnimplementedQuotaServiceServer
// for forward compatibility.
type QuotaServiceServer interface {
	ReserveSubscriptionSlot(context.Context, *ReserveSubscriptionSlotRequest) (*ReserveSubscriptionSlotResponse, error)
	CommitSubscriptionSlot(context.Context, *CommitSubscriptionSlotRequest) (*CommitSubscriptionSlotResponse, error)
	ReleaseSubscriptionSlot(context.Context, *ReleaseSubscriptionSlotRequest) (*ReleaseSubscriptionSlotResponse, error)
	mustEmbedUnimplementedQuotaServiceServer()
}

// UnimplementedQuotaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuotaServiceServer struct{}

func (UnimplementedQuotaServiceServer) ReserveSubscriptionSlot(context.Context, *ReserveSubscriptionSlotRequest) (*ReserveSubscriptionSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveSubscriptionSlot not implemented")
}
func (UnimplementedQuotaServiceServer) CommitSubscriptionSlot(context.Context, *CommitSubscriptionSlotRequest) (*CommitSubscriptionSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitSubscriptionSlot not implemented")
}
func (UnimplementedQuotaServiceServer) ReleaseSubscriptionSlot(context.Context, *ReleaseSubscriptionSlotRequest) (*ReleaseSubscriptionSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseSubscriptionSlot not implemented")
}
func (UnimplementedQuotaServiceServer) mustEmbedUnimplementedQuotaServiceServer() {}
func (UnimplementedQuotaServiceServer) testEmbeddedByValue()                      {}

// UnsafeQuotaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuotaServiceServer will
// result in compilation errors.
type UnsafeQuotaServiceServer interface {
	mustEmbedUnimplementedQuotaServiceServer()
}

func RegisterQuotaServiceServer(s grpc.ServiceRegistrar, srv QuotaServiceServer) {
	// If the following call pancis, it indicates UnimplementedQuotaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuotaService_ServiceDesc, srv)
}

func _QuotaService_ReserveSubscriptionSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveSubscriptionSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotaServiceServer).ReserveSubscriptionSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuotaService_ReserveSubscriptionSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotaServiceServer).ReserveSubscriptionSlot(ctx, req.(*ReserveSubscriptionSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuotaService_CommitSubscriptionSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitSubscriptionSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotaServiceServer).CommitSubscriptionSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuotaService_CommitSubscriptionSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotaServiceServer).CommitSubscriptionSlot(ctx, req.(*CommitSubscriptionSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuotaService_ReleaseSubscriptionSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSubscriptionSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotaServiceServer).ReleaseSubscriptionSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuotaService_ReleaseSubscriptionSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotaServiceServer).ReleaseSubscriptionSlot(ctx, req.(*ReleaseSubscriptionSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuotaService_ServiceDesc is the grpc.ServiceDesc for QuotaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuotaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quota.QuotaService",
	HandlerType: (*QuotaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveSubscriptionSlot",
			Handler:    _QuotaService_ReserveSubscriptionSlot_Handler,
		},
		{
			MethodName: "CommitSubscriptionSlot",
			Handler:    _QuotaService_CommitSubscriptionSlot_Handler,
		},
		{
			MethodName: "ReleaseSubscriptionSlot",
			Handler:    _QuotaService_ReleaseSubscriptionSlot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/quota/quota.proto",
}
